### PR TITLE
Fix/vicjohn447 plant icons

### LINKED ISSUE #19: Icons for different plant types
Add icons to differentiate between the different flora growing in UWA. I believe we will require at least 3 different icons to differentiate the various plants. Adding colours to the icons will help differentiate it even further.

[Material Design Icons](https://materialdesignicons.com/) is the icon library used for this project.

### PR DESCRIPTION
**Pull request by VicJohn447**
New plant icons all have been tested and work as intended on the map page. 

Fixes #19

### CODE REVIEW

**Review by JeremiahPinto — CHANGES_REQUESTED** [review]
The values of the icon colours will be pulled from the database, move all variables except path to where the array is used

**Comment by VicJohn447** [comment]
Just want to confirm, I need to move everything except the icon's path to plantDB.json?

If so that would mean being able to make separate colours that suit each different plant. I wonder if we're going to go down this route or just use one colour for each icon.

**Comment by Drewbi** [comment]
Why/How/Where will the colours come from? are we making a new model for icons? @JeremiahPinto

**Comment by JeremiahPinto** [comment]
The colours would come from the db as part of the flora request. @Drewbi will have to add that field in if it isn't already there. To answer your question, yes the colours would be different for each of them but we also need a default colour set to them. Right now it will be done in the frontend, but the default will be handled in the db

**Pull request closed without merging**
